const productInfo = [
  {
    new: true,
    sale: false,
    liked: true,
    brand: "brand name",
    title: "Zipper Mini Dress",
    price: 879.0,
    img: "../assets/dressBlue.png",
    icons: [1, 2, 3],
  },
  {
    new: true,
    sale: false,
    liked: true,
    brand: "brand name",
    title: "Zipper Mini Dress",
    price: 879.0,
    img: "../assets/dressRed.png",
    icons: [1, 2],
  },
  {
    new: true,
    sale: false,
    liked: true,
    brand: "brand name",
    title: "Zipper Mini Dress",
    price: 879.0,
    img: "../assets/dressBlack.png",
    icons: [1, 2, 3],
  },
  {
    new: true,
    sale: false,
    liked: true,
    brand: "brand name",
    title: "Zipper Mini Dress",
    price: 879.0,
    img: "../assets/dressBlue.png",
    icons: [3],
  },
  {
    new: true,
    sale: false,
    liked: true,
    brand: "brand name",
    title: "Zipper Mini Dress",
    price: 879.0,
    img: "../assets/dressRed.png",
    icons: [1, 2, 3],
  },
  {
    new: true,
    sale: true,
    liked: true,
    brand: "brand name",
    title: "Zipper Mini Dress",
    price: 879.0,
    img: "../assets/dressBlack.png",
    icons: [1, 2, 3],
  },
];
